netty-ports:
  basic: 8080
  basic2: 8081

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    level:
  file:
    name: /test/program/logs/service.log
  logback:
    rollingpolicy:
      max-history: 15
      file-name-pattern: "/test/program/logs/service.log.%d{yyyy-MM-dd}.%i"
  level:
    root: info
